version: '3'

services:
  mariadb:
    image: mariadb:sql
    build: ./requirements/mariadb
    volumes:
      - maria_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - wp_db
    restart: always

  wordpress:
    image: wordpress:fpm
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wp_data:/var/www/html
    env_file:
      - .env
    networks:
      - wp_db
    restart: always

  nginx:
    image: nginx:ssl
    build: ./requirements/nginx
    depends_on:
      - wordpress
    volumes:
      - wp_data:/var/www/html
    ports:
      - 443:443
    networks:
      - wp_db
    restart: always


volumes:
  maria_data:
   driver_opts:
      type: none
      o: bind
      device: /home/ykhayri/data/maria
  wp_data:
   driver_opts:
      type: none
      o: bind
      device: /home/ykhayri/data/wordp

networks:
  wp_db: